let bulgare = [
	{"letter" : {"uppercase" : "A", "lowercase" : "а"},
		"prononciation" : {"son" : "a",
			"explanation" : "(sous accent, prononcé comme dans \"ma\"," +
			" hors accent, atténué, proche de \"oe\" dans \"beurre\")" },
	"words" : {"0": ['Ангел', 'Ange'],
	  			"1" : ['Aдрес', 'Adresse']}},
  {"letter" : {"uppercase" : "Б", "lowercase" : "б"}, "prononciation" : {"son" : "b", "explanation" : "" },
	"words" : {"0": ['Бира', 'Bière'],
    "1" : ['Банка', 'Banque']}},
	{"letter" : {"uppercase" : "В", "lowercase" : "в"}, "prononciation" : {"son" : "v", "explanation" : "" },
	"words" : {"0": ["Вагон", "Wagon"],
      "1" : ['Виза', 'Visa']}},
	{"letter" : {"uppercase" : "Г", "lowercase" : "г"}, "prononciation" : {"son" : "g", "explanation" : "comme dans gare" }, "words" : {"0": ["Газ", "Gaz"],
        "1" : ['Гараж', 'Garage']}},
	{"letter" : {"uppercase" : "Д", "lowercase" : "д-g"}, "prononciation" : {"son" : "d", "explanation" : ""},
	"words" : {"0": ["Добре", "Bien"],
      "1" : ['Доктор', 'Docteur']}},
	{"letter" : {"uppercase" : "Е", "lowercase" : "е"}, "prononciation" : {"son" : "è / é", "explanation" : "è de \"mère\" sous accent, " +
	"é de \"pré\" hors accent." }, "words" : {"0": ["Елен", "Cerf"],
        "1" : ['Eкран', 'Ecran']}},
	{"letter" : {"uppercase" : "Ж", "lowercase" : "ж"}, "prononciation" : {"son" : "j", "explanation" : "" },
	"words" : {"0": ["Жаба","Grenouille"],
      "1" : ['Bижу', 'bijou']}},
	{"letter" : {"uppercase" : "З", "lowercase" : "з"}, "prononciation" : {"son" : "z", "explanation" : "" },
	"words" : {"0": ["Зa", "Pour"],
      "1" : ['Физика', 'physique']}},
	{"letter" : {"uppercase" : "И", "lowercase" : "и"}, "prononciation" : {"son" : "i", "explanation" : "" },
	"words" : {"0": ["Игла", "Aiguille"],
      "1" : ['Риск', 'risque']}},
	{"letter" : {"uppercase" : "Й", "lowercase" : "й"}, "prononciation" : {"son" : "ï", "explanation" : "comme dans \"yak\" ou " +
	"ill dans \"paille\"." }, "words" : {"0": ["Йод", "Iode"],
        "1" : ['Tролей', 'Trolley bus']}},
	{"letter" : {"uppercase" : "К", "lowercase" : "к"}, "prononciation" : {"son" : "k", "explanation" : "" }, "words" : {"0": ["Клас", "Classe"],
        "1" : ['Кафе', 'Café']}},
	{"letter" : {"uppercase" : "Л", "lowercase" : "л"}, "prononciation" : {"son" : "l", "explanation" : "dur devant a, o, y, ъ, " +
	"prononcé comme en français devant e, и, ю, я. " },
	 "words" : {"0": ["Лава", "Lave"],
       "1" : ['Луна', 'lune']}},
	{"letter" : {"uppercase" : "М", "lowercase" : "м"}, "prononciation" : {"son" : "m", "explanation" : "" },
		"words" : {"0": ['Музика', 'Musique'],
          "1" : ['Мустак', 'Moustache']}},
	{"letter" : {"uppercase" : "Н", "lowercase" : "н"}, "prononciation" : {"son" : "n	", "explanation" : "" },
		"words" : {"0": ["Не", "Non"],
          "1" : ['Номер', 'Numéro']}},
	{"letter" : {"uppercase" : "О", "lowercase" : "о"}, "prononciation" : {"son" : "o / ô", "explanation" : "o ouvert sous accent," +
	" ô fermé hors accent." }, "words" : {"0": ["Обяд", "Déjeuner"],
        "1" : ['Фолклор', 'Folklore']}},
	{"letter" : {"uppercase" : "П", "lowercase" : "п"}, "prononciation" : {"son" : "p", "explanation" : "" },
		"words" : {"0":  ["Пак", "encore"],
          "1" : ['Професор', 'Professeur']}},
	{"letter" : {"uppercase" : "Р", "lowercase" : "р"}, "prononciation" : {"son" : "r", "explanation" : "(toujours roulé)" }, "words" : {"0": ["Рок", "Rock"],
        "1" : ['Ресторант', 'Restaurant']}},
	{"letter" : {"uppercase" : "С", "lowercase" : "с"}, "prononciation" : {"son" : "s / ss", "explanation" : "" },
		"words" : {"0": ["Скоро", "Bientôt"],
          "1" : ['Салата', 'Salade']}},
	{"letter" : {"uppercase" : "Т", "lowercase" : "т - m"}, "prononciation" : {"son" : "t", "explanation" : "" },
		"words" : {"0":  ["Тест", "Tester"],
          "1" : ['Tакси', 'Taxi']}},
	{"letter" : {"uppercase" : "У", "lowercase" : "у"}, "prononciation" : {"son" : "ou", "explanation" : "" },
		"words" : {"0":  ["Удар", "Coup"],
          "1" : ['Tурист', 'Touriste']}},
	{"letter" : {"uppercase" : "Ф", "lowercase" : "ф"}, "prononciation" : {"son" : "f", "explanation" : "" },
		"words" : {"0": ["Факт", "Fait"],
          "1" : ['Франция', 'France']}},
	{"letter" : {"uppercase" : "Х", "lowercase" : "х"}, "prononciation" : {"son" : "kh", "explanation" : "ce son n'existe pas en français." }, "words" : {"0": ["Хумор", "Humour"],
        "1" : ['Хотел', 'Hôtel']}},
	{"letter" : {"uppercase" : "Ц", "lowercase" : "ц"}, "prononciation" : {"son" : "ts", "explanation" : "" },
		"words" : {"0": ["Цар", "Roi"],
          "1" : ['Процедура', 'Procédure']}},
	{"letter" : {"uppercase" : "Ч", "lowercase" : "ч"}, "prononciation" : {"son" : "tch", "explanation" : "" },
		"words" : {"0": ["Чар", "Charme"],
          "1" : ['Четири', 'Quatre']}},
	{"letter" : {"uppercase" : "Ш", "lowercase" : "ш"}, "prononciation" : {"son" : "ch", "explanation" : "" }, "words" : {"0":  ["Шал", "Écharpe"],
        "1" : ['Душ', 'Douche']}},
	{"letter" : {"uppercase" : "Щ", "lowercase" : "щ"}, "prononciation" : {"son" : "cht", "explanation" : "" },
		"words" : {"0": ["Щат", "Etat"],
          "1" : ['Поща', 'Poste']}},
	{"letter" : {"uppercase" : "Ъ", "lowercase" : "ъ"}, "prononciation" : {"son" : "eu", "explanation" : "proche du \"eu\" de \"beure\" sous l'accent, " +
	"plus relâché, se rapprochant légèrement de a hors accent." }, "words" : {"0": ["Ъгъл", "Angle"],
        "1" : ['България', 'Bulgarie']} },
	{"letter" : {"uppercase" : "Ь", "lowercase" : "Ь"}, "prononciation" : {"son" : "io", "explanation" : "seulement dans la combinaison bo" }, "words" : {"0": ["Миньор", "Mineur"],
        "1" : ['Шофьoр', 'Chauffeur']}},
	{"letter" : {"uppercase" : "Ю", "lowercase" : "ю"}, "prononciation" : {"son" : "iou", "explanation" : "prononcé en une seule syllabe." }, "words" : {"0": ["Юли", "Juillet"],
        "1" : ['Парфюм', 'Parfum']}},
	{"letter" : {"uppercase" : "Я", "lowercase" : "я"}, "prononciation" : {"son" : "ia", "explanation" : "prononcé en une seule syllabe." }, "words" : {"0": ["Ям", "Manger"],
        "1" : ['Tеория', 'Théorie']}}
];

export default bulgare;