let bulgare = [
	{"letter" : {"uppercase" : "A", "lowercase" : "a"},
		"prononciation" : {"son" : "a",
			"explanation" : "(sous accent, prononcé comme dans \"ma\"," +
			" hors accent, atténué, proche de \"oe\" dans \"beurre\")" },
	"words" : ['Ангел', 'Ange']},
	{"letter" : {"uppercase" : "Б", "lowercase" : "б"}, "prononciation" : {"son" : "b", "explanation" : "" },
	"words" : ['Бира', 'Bière']},
	{"letter" : {"uppercase" : "В", "lowercase" : "в"}, "prononciation" : {"son" : "v", "explanation" : "" },
	"words" : ["Вагон", "Wagon"]},
	{"letter" : {"uppercase" : "Г", "lowercase" : "г"}, "prononciation" : {"son" : "g", "explanation" : "comme dans gare" }, "words" : ["Газ", "Gaz"]},
	{"letter" : {"uppercase" : "Д", "lowercase" : "д-g"}, "prononciation" : {"son" : "d", "explanation" : ""},
	"words" : ["Добре", "Bien"]},
	{"letter" : {"uppercase" : "Е", "lowercase" : "е"}, "prononciation" : {"son" : "è / é", "explanation" : "è de \"mère\" sous accent, " +
	"é de \"pré\" hors accent." }, "words" : ["Елен", "Cerf"]},
	{"letter" : {"uppercase" : "Ж", "lowercase" : "ж"}, "prononciation" : {"son" : "j", "explanation" : "" },
	"words" : ["Жаба","Grenouille"]},
	{"letter" : {"uppercase" : "З", "lowercase" : "з"}, "prononciation" : {"son" : "z", "explanation" : "" },
	"words" : ["Зa", "Pour"]},
	{"letter" : {"uppercase" : "И", "lowercase" : "и"}, "prononciation" : {"son" : "i", "explanation" : "" },
	"words" : ["Игла", "Aiguille"]},
	{"letter" : {"uppercase" : "Й", "lowercase" : "й"}, "prononciation" : {"son" : "ï", "explanation" : "comme dans \"yak\" ou " +
	"ill dans \"paille\"." }, "words" : ["Йод", "Iode"]},
	{"letter" : {"uppercase" : "К", "lowercase" : "к"}, "prononciation" : {"son" : "k", "explanation" : "" }, "words" : ["Клас", "Classe"]},
	{"letter" : {"uppercase" : "Л", "lowercase" : "л"}, "prononciation" : {"son" : "l", "explanation" : "dur devant a, o, y, ъ, " +
	"prononcé comme en français devant e, и, ю, я. " },
	 "words" : ["Лава", "Lave"]},
	{"letter" : {"uppercase" : "М", "lowercase" : "м"}, "prononciation" : {"son" : "m", "explanation" : "" },
		"words" : ["Мадама", "Madame"]},
	{"letter" : {"uppercase" : "Н", "lowercase" : "н"}, "prononciation" : {"son" : "n	", "explanation" : "" },
		"words" : ["Не", "Non"]},
	{"letter" : {"uppercase" : "О", "lowercase" : "о"}, "prononciation" : {"son" : "o / ô", "explanation" : "o ouvert sous accent," +
	" ô fermé hors accent." }, "words" : ["Обяд", "Déjeuner"]},
	{"letter" : {"uppercase" : "П", "lowercase" : "п"}, "prononciation" : {"son" : "p", "explanation" : "" },
		"words" : ["Пак", "encore"]},
	{"letter" : {"uppercase" : "Р", "lowercase" : "р"}, "prononciation" : {"son" : "r", "explanation" : "(toujours roulé)" }, "words" : ["Рок", "Rock"]},
	{"letter" : {"uppercase" : "С", "lowercase" : "с"}, "prononciation" : {"son" : "s / ss", "explanation" : "" },
		"words" : ["Скоро", "Bientôt"]},
	{"letter" : {"uppercase" : "Т", "lowercase" : "т - m"}, "prononciation" : {"son" : "t", "explanation" : "" },
		"words" : ["Тест", "Tester"]},
	{"letter" : {"uppercase" : "У", "lowercase" : "у"}, "prononciation" : {"son" : "ou", "explanation" : "" },
		"words" : ["Удар", "Coup"]},
	{"letter" : {"uppercase" : "Ф", "lowercase" : "ф"}, "prononciation" : {"son" : "f", "explanation" : "" },
		"words" : ["Факт", "Fait"]},
	{"letter" : {"uppercase" : "Х", "lowercase" : "х"}, "prononciation" : {"son" : "kh", "explanation" : "ce son n'existe pas en français." }, "words" : ["Хол", "Salon"]},
	{"letter" : {"uppercase" : "Ц", "lowercase" : "ц"}, "prononciation" : {"son" : "ts", "explanation" : "" },
		"words" : ["Цар", "Roi"]},
	{"letter" : {"uppercase" : "Ч", "lowercase" : "ч"}, "prononciation" : {"son" : "tch", "explanation" : "" },
		"words" : ["Чар", "Charme"]},
	{"letter" : {"uppercase" : "Ш", "lowercase" : "ш"}, "prononciation" : {"son" : "ch", "explanation" : "" }, "words" : ["Шал", "Écharpe"]},
	{"letter" : {"uppercase" : "Щ", "lowercase" : "щ"}, "prononciation" : {"son" : "cht", "explanation" : "" },
		"words" : ["Щат", "Etat"]},
	{"letter" : {"uppercase" : "Ъ", "lowercase" : "ъ"}, "prononciation" : {"son" : "eu", "explanation" : "proche du \"eu\" de \"beure\" sous l'accent, " +
	"plus relâché, se rapprochant légèrement de a hors accent." }, "words" : ["Ъгъл", "Angle"]},
	{"letter" : {"uppercase" : "Ь", "lowercase" : "Ь"}, "prononciation" : {"son" : "io", "explanation" : "seulement dans la combinaison bo" }, "words" : ["Миньор", "Mineur"]},
	{"letter" : {"uppercase" : "Ю", "lowercase" : "ю"}, "prononciation" : {"son" : "iou", "explanation" : "prononcé en une seule syllabe." }, "words" : ["Юли", "Juillet"]},
	{"letter" : {"uppercase" : "Я", "lowercase" : "я"}, "prononciation" : {"son" : "ia", "explanation" : "prononcé en une seule syllabe." }, "words" : ["Ям", "Manger"]}
];

export default bulgare;