let bulgare = [
	{"letter" : {"uppercase" : "A", "lowercase" : "a"}, "prononciation" : "a"},
	{"letter" : {"uppercase" : "Б", "lowercase" : "б"}, "prononciation" : "b"},
	{"letter" : {"uppercase" : "В", "lowercase" : "в"}, "prononciation" : "a"},
	{"letter" : {"uppercase" : "Г", "lowercase" : "г"}, "prononciation" : "gu"},
	{"letter" : {"uppercase" : "Д", "lowercase" : "д ou g"}, "prononciation" : "d"},
	{"letter" : {"uppercase" : "Е", "lowercase" : "е"}, "prononciation" : "é"},
	{"letter" : {"uppercase" : "Ж", "lowercase" : "ж"}, "prononciation" : "j"},
	{"letter" : {"uppercase" : "З", "lowercase" : "a"}, "prononciation" : "z"},
	{"letter" : {"uppercase" : "И", "lowercase" : "a"}, "prononciation" : "i"},
	{"letter" : {"uppercase" : "Й", "lowercase" : "й"}, "prononciation" : "y"},
	{"letter" : {"uppercase" : "К", "lowercase" : "к"}, "prononciation" : "k"},
	{"letter" : {"uppercase" : "Л", "lowercase" : "л"}, "prononciation" : "l"},
	{"letter" : {"uppercase" : "М", "lowercase" : "м"}, "prononciation" : "m"},
	{"letter" : {"uppercase" : "Н", "lowercase" : "н"}, "prononciation" : "n"},
	{"letter" : {"uppercase" : "О", "lowercase" : "о"}, "prononciation" : "o"},
	{"letter" : {"uppercase" : "П", "lowercase" : "п"}, "prononciation" : "p"},
	{"letter" : {"uppercase" : "Р", "lowercase" : "р"}, "prononciation" : "r"},
	{"letter" : {"uppercase" : "С", "lowercase" : "с"}, "prononciation" : "s"},
	{"letter" : {"uppercase" : "Т", "lowercase" : "т ou m"}, "prononciation" : "t"},
	{"letter" : {"uppercase" : "У", "lowercase" : "у"}, "prononciation" : "ou"},
	{"letter" : {"uppercase" : "Ф", "lowercase" : "ф"}, "prononciation" : "f"},
	{"letter" : {"uppercase" : "Х", "lowercase" : "х"}, "prononciation" : "kh"},
	{"letter" : {"uppercase" : "Ц", "lowercase" : "ц"}, "prononciation" : "ts"},
	{"letter" : {"uppercase" : "Ч", "lowercase" : "ч"}, "prononciation" : "tch"},
	{"letter" : {"uppercase" : "Ш", "lowercase" : "ш"}, "prononciation" : "ch"},
	{"letter" : {"uppercase" : "Щ", "lowercase" : "щ"}, "prononciation" : "cht"},
	{"letter" : {"uppercase" : "Ъ", "lowercase" : "ъ"}, "prononciation" : "eu"},
	{"letter" : {"uppercase" : "Ь", "lowercase" : "Ь"}, "prononciation" : "signe mou"},
	{"letter" : {"uppercase" : "Ю", "lowercase" : "Ю"}, "prononciation" : "you"},
	{"letter" : {"uppercase" : "Я", "lowercase" : "я"}, "prononciation" : "ya"},

];

export default bulgare;